permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: going1000
  email: miaorenjin@gmail.com
  link: http://going1000.github.io
  github: http://github.com/going1000

# 站点信息
title: going1000s blog
description: going1000s blog
url: http://going1000.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://yansu-uploads.stor.sinaapp.com/imgs/gavatar.png
favicon: http://yansu-uploads.stor.sinaapp.com/imgs/favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: suyan-zh

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
